/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.9.1.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as addFriend from "../addFriend";
import type * as listFriends from "../listFriends";
import type * as listMessages from "../listMessages";
import type * as listPosts from "../listPosts";
import type * as login from "../login";
import type * as register from "../register";
import type * as searchUsers from "../searchUsers";
import type * as sendMessage from "../sendMessage";
import type * as submitPost from "../submitPost";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  addFriend: typeof addFriend;
  listFriends: typeof listFriends;
  listMessages: typeof listMessages;
  listPosts: typeof listPosts;
  login: typeof login;
  register: typeof register;
  searchUsers: typeof searchUsers;
  sendMessage: typeof sendMessage;
  submitPost: typeof submitPost;
}>;
